// <auto-generated />
using System;
using System.Text.Json;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace worklinnEdu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803151511_UpdateResponseSchema")]
    partial class UpdateResponseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbModels.Field", b =>
                {
                    b.Property<string>("FieldId")
                        .HasColumnType("text")
                        .HasColumnName("field_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<bool>("FieldRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("field_required");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_type");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_id");

                    b.HasKey("FieldId");

                    b.HasIndex("FormId");

                    b.ToTable("field", "core");
                });

            modelBuilder.Entity("DbModels.Form", b =>
                {
                    b.Property<string>("FormId")
                        .HasColumnType("text")
                        .HasColumnName("form_id");

                    b.Property<bool>("FormClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("form_closed");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_name");

                    b.HasKey("FormId");

                    b.ToTable("form", "core");
                });

            modelBuilder.Entity("DbModels.Response", b =>
                {
                    b.Property<string>("SubmissionId")
                        .HasColumnType("text")
                        .HasColumnName("submission_id");

                    b.Property<string>("FormId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_id");

                    b.Property<string>("RespondentId")
                        .HasColumnType("text")
                        .HasColumnName("respondent_id");

                    b.Property<JsonElement>("ResponseData")
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("SubmissionId");

                    b.HasIndex("FormId");

                    b.ToTable("response", "responses");
                });

            modelBuilder.Entity("DbModels.Field", b =>
                {
                    b.HasOne("DbModels.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("DbModels.Response", b =>
                {
                    b.HasOne("DbModels.Form", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("DbModels.Form", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
