// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace worklinnEdu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbModels.Form", b =>
                {
                    b.Property<string>("FormId")
                        .HasColumnType("text")
                        .HasColumnName("form_id");

                    b.Property<string>("EventTitle")
                        .HasColumnType("text")
                        .HasColumnName("event_title");

                    b.Property<string>("HsEvents")
                        .HasColumnType("text")
                        .HasColumnName("hs_events");

                    b.Property<string>("HssEvents")
                        .HasColumnType("text")
                        .HasColumnName("hss_events");

                    b.Property<string>("LpEvents")
                        .HasColumnType("text")
                        .HasColumnName("lp_events");

                    b.Property<string>("UpEvents")
                        .HasColumnType("text")
                        .HasColumnName("up_events");

                    b.HasKey("FormId");

                    b.ToTable("forms", "core");
                });

            modelBuilder.Entity("DbModels.Kdrrod", b =>
                {
                    b.Property<string>("SubmissionId")
                        .HasColumnType("text")
                        .HasColumnName("submission_id");

                    b.Property<string>("Classification")
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<string>("Events")
                        .HasColumnType("text")
                        .HasColumnName("events");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RespondentId")
                        .HasColumnType("text")
                        .HasColumnName("respondent_id");

                    b.Property<string>("RollNo")
                        .HasColumnType("text")
                        .HasColumnName("roll_no");

                    b.Property<string>("StudentClass")
                        .HasColumnType("text")
                        .HasColumnName("student_class");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("SubmissionId");

                    b.ToTable("kdrrod", "responses");
                });
#pragma warning restore 612, 618
        }
    }
}
